#page title
page_title                                : SpamBuster # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1471555874 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/ru/app/id1471555874 # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :
presskit_download_link                    :

app_icon                                  : assets/AppIcon.png # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : SpamBuster # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Больше никаких незнакомых номеров! # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Прокачай свой телефон, установи автоматический определитель и блокировщик номеров, бесплатно и без рекламы.

enable_smart_app_banner                   : true # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 :                                 
your_link                                 :                      
your_city                                 :                                 
email_address                             : roma6125@yandex.ru
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : roma6125
github_username                           : roma6125
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Определитель
    description                           : Включите проверку входящих звонков и решайте сами, стоит ли брать трубку. Данные о номере будут отображаться прямо на экране вашего телефона, во время звонка. Следите за обновлениями, мы постоянно пополняем нашу базу номеров.
    fontawesome_icon_name                 : search

  - title                                 : Антиспам
    description                           : Блокируйте спамеров и помогайте другим. Активируйте функцию и блокируйте номера злоумышленников одним движением, прямо из истории звонков. Данные о спамерах автоматически попадают в антиспам базы других пользователей.
    fontawesome_icon_name                 : shield-alt

  - title                                 : Премиум
    description                           : Подключите автоблокировку и забудьте о назойливых спам звонках. Телефон будет сам автоматически скрывать все вызовы от нежелательных номеров.
    fontawesome_icon_name                 : star


  - title                                 : Безопасно
    description                           : Приложение не требует регистрации. У нас нет доступа к вашим контактам и звонкам. Мы ценим вашу приватность и собираем только номера нежелательных абонентов.
    fontawesome_icon_name                 : exclamation

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : # Replace with alternative image path or image URL.
cover_overlay_color                       : "#545454"
cover_overlay_transparency                : 1.0

device_color                              : black # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown